#!/sbin/sh

OUTFD=/proc/self/fd/$2;

ui_print() {
  until [ ! "$1" ]; do
    echo -e "ui_print $1\nui_print" > $OUTFD;
    shift;
  done;
}

ui_print "update-binary triggered";
umount /system;
mount /system;
umount /data;
mount /data;
echo "1" > /data/property/persist.sys.safemode;
chmod 600 /data/property/persist.sys.safemode;
ui_print "U may try if it boots into safe mode"
